---
title: Data check
author: Masatoshi Katabuchi
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
#rmdformats::material
  html_document:
    fig_caption: yes
    theme: spacelab #readable #sandstone #spacelab #flatly
    highlight: pygments #tango #kate
    toc: TRUE
    toc_depth: 2
    number_sections: TRUE
    toc_float:
      collapsed: TRUE
      smooth_scroll: TRUE
      toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, data, include=FALSE}
library(tidyverse)
library(GGally)
library(tictoc)
library(FactoMineR)
#install.packages("factoextra")
library(factoextra)
theme_set(theme_light())

#seedling_all <- read_csv("../data/seedling_for_drought.csv")
seedling_all <- read_csv("../data/seedlingmatrix.csv")

#trait0 <- read_csv("./data/BB_SeedlingTrait.csv")
trait <- read_csv("../data/trait SPcode.csv")

#trait <- trait %>% 
#  select(-Cname) %>%
#  rename(StemD = WD)


```

# Covariance

## Demography

```{r demo-cov, cache=TRUE, message=FALSE, warning=FALSE}
seedling_all %>%
  dplyr::select(CONS, CONA, HETS, HETA) %>%
  ggpairs(.)
```

## Traits

### Missing data

```{r}
is.na(trait) %>%
  apply(., 2, sum)
```

### Histogram

```{r}
trait %>%
  pivot_longer(LDMC:tlp) %>%
  ggplot(., aes(x = value)) +
  geom_histogram() +
  facet_wrap(~ name, scale = "free")
```

```{r}
trait2 <- trait %>%
  mutate(logLA = log(LA)) %>%
  mutate(logSLA = log(SLA)) %>%
  mutate(logLT = log(LT)) %>%
  dplyr::select(-LA, -SLA, -LT)

trait2 %>%
  pivot_longer(LDMC:logLT) %>%
  ggplot(., aes(x = value)) +
  geom_histogram() +
  facet_wrap(~ name, scale = "free")
```

### Pair plot

```{r trait-cov, cache=TRUE, message=FALSE, warning=FALSE, fig.width=12, fig.height=12}
tic()
trait2 %>%
  dplyr::select(-SPcode) %>%
  ggpairs(trait2)
toc()
```

### PCA

*Original PCA*

```{r}

trait_pca <- prcomp(trait2 %>% 
                    dplyr::select(-SPcode) %>%
                    na.omit, scale = TRUE, center = TRUE)

df <- facto_summarize(trait_pca, element = "var", 
                     result = c("coord", "contrib", "cos2"), axes = c(1,2))
colnames(df)[2:3] <-  c("x", "y")

# need this to calc scale
pca_ind <- get_pca_ind(trait_pca)
ind <- data.frame(pca_ind$coord[, c(1,2), drop=FALSE], stringsAsFactors = TRUE)
colnames(ind)<- c("x", "y")

# rescale variable coordinates
r <- min(
(max(ind[,"x"])-min(ind[,"x"])/(max(df[,"x"])-min(df[,"x"]))),
(max(ind[,"y"])-min(ind[,"y"])/(max(df[,"y"])-min(df[,"y"])))
)

```

```{r}
summary(trait_pca)
```

- `labels = FALSE`
- `mean.point = FALSE`

```{r}

fviz_pca_biplot(trait_pca, axes.linetype = "dotted", 
                col.var = "black", 
                geom = "text",
                alpha.ind = 0.4, 
                geom.ind = "point",
                addEllipses = FALSE,
                label = "var",
                mean.point = FALSE,
                repel = TRUE   # Avoid text overlapping
                ) 


```

```{r}
fviz_pca_biplot(trait_pca, axes.linetype = "dotted", 
                col.var = "black", 
                geom = "text",
                axes = c(1, 3),
                alpha.ind = 0.4, 
                geom.ind = "point",
                addEllipses = FALSE,
                label = "var",
                mean.point = FALSE,
                repel = TRUE   # Avoid text overlapping
                ) 
```

```{r}
fviz_pca_biplot(trait_pca, axes.linetype = "dotted", 
                col.var = "black", 
                geom = "text",
                axes = c(2, 3),
                alpha.ind = 0.4, 
                geom.ind = "point",
                addEllipses = FALSE,
                label = "var",
                mean.point = FALSE,
                repel = TRUE   # Avoid text overlapping
                ) 
```

```{r}

trait3 <- trait2 %>% 
  dplyr::select(WD, logSLA, logLT) %>%
  na.omit

trait_pca2 <- prcomp(trait3,
                  scale = TRUE, center = TRUE)

fviz_pca_biplot(trait_pca2, axes.linetype = "dotted", 
                col.var = "black", 
                geom = "text",
                alpha.ind = 0.4, 
                geom.ind = "point",
                addEllipses = FALSE,
                label = "var",
                mean.point = FALSE,
                repel = TRUE   # Avoid text overlapping
                ) 
```

```{r, eval = TRUE}
qplot(data= trait2, x = logLA, y = tlp)
```

# Species-level model options

Collinearity will be fine except for stem density and SDMC. We will check the
following models.

All species

- Full
- removing StemD from the full model
- Intercept + PC1 + PC2 + PC3 (66%)

