---
title: LKJ
author: Masatoshi Katabuchi
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
#rmdformats::material
  html_document:
    fig_caption: yes
    theme: spacelab #readable #sandstone #spacelab #flatly
    highlight: pygments #tango #kate
    toc: TRUE
    toc_depth: 2
    number_sections: TRUE
    toc_float:
      collapsed: TRUE
      smooth_scroll: TRUE
      toc: true
---

```{r, echo = F}
rm(list = ls())
```

```{r}
library(rstan)
rstan::rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores()) # Run on multiple cores

```

# LKJ

```{r}

expose_stan_functions("../model/lkj.stan")

rho <- numeric(0)
eta <- c(0.7, 1, 2, 4)
for (i in 1:length(eta)) {
  lkj2 <- replicate(1e4, lkj_cor_rng(2, eta[i]))
  rho <- cbind(rho, apply(lkj2, 3, function(x) x[1, 2]))
}
colnames(rho) <- c("eta = 0.7", "eta = 1", "eta = 2", "eta = 4")
rho <- tidyr::gather(as.data.frame(rho))

qplot(value, alpha = I(1/3), geom = "histogram", data = rho) +
  xlab(expression(rho)) + facet_wrap(~key)

```

```{r}

set.seed(2) # for reproducibility
sig1 <- 0.2
sig2 <- 0.3
rho <- -0.4


(sigma <- matrix(c(sig1^2, sig1*sig2*rho, sig1*sig2*rho, sig2^2), nrow = 2))

y <- mvtnorm::rmvnorm(100, mean = c(0, 0), sigma = sigma)

qplot(y[, 1], y[, 2])


cor(y)

```

Sample correlation is `r round(cor(y)[1,2], 2)`

# Simulation

## Model - wishart?

```{stan, output.var="ex0", cache=TRUE}
data {
  int<lower=0> n;
  vector[2] y[n];
}
parameters {
  vector[2] mu;
  cov_matrix[2] Sigma;
}
model {
  mu ~ normal(0, 1);
  y ~ multi_normal(mu, Sigma);
}
```

```{r}
n <- nrow(y)
data <- list(y = y, n = n)
s1fit <- sampling(ex0, iter = 500, chains = 4, data = data)
Sigma <- extract(s1fit, pars = "Sigma")$Sigma
# For each posterior draw, pull out the covariance matrix,
# convert it to correlation matrix, and pull out the correlation rho
rho1 <- apply(Sigma, 1, function(x) cov2cor(x)[1, 2])

qplot(rho1, alpha = I(1/2)) +
  geom_vline(xintercept = mean(rho1), colour = "red") +
  geom_vline(xintercept = cor(y)[1,2], colour = "blue")

s1fit

mean(rho1)
```


## Model - LKJ

```{stan, output.var="ex1", cache=TRUE}
data {
  int<lower = 1> N;    // number of observations
  int<lower = 1> J;    // number of outcome variables (2 in our case)
  vector[J] y[N];      // observations
  real<lower = 0> eta; // shape parameter for LKJ ditribution
}
parameters {
  vector[J] mu;
  cholesky_factor_corr[J] L_Omega;
  vector<lower=0>[J] L_sigma;
}
model {
  L_Omega ~ lkj_corr_cholesky(eta);
  L_sigma ~ cauchy(0, 2.5);
  mu ~ normal(0, 1);
  y ~ multi_normal_cholesky(mu, diag_pre_multiply(L_sigma, L_Omega));
}
generated quantities {
  corr_matrix[J] Omega;
  Omega = multiply_lower_tri_self_transpose(L_Omega);
}
```



### $\eta$ = 1

```{r}

data <- list(N = nrow(y), J = 2, y = y, eta = 1) # uniform on -1 to 1
#s2model <- stan_model("sigma2.stan")
s2fit <- sampling(ex1, iter = 500, chains = 4, data = data)
s2draws <- extract(s2fit)
Omega <- s2draws$Omega
rho2 <- apply(Omega, 2, function(x) x[,1])[, 2]

qplot(rho2, alpha = I(1/2)) +
  geom_vline(xintercept = mean(rho2), colour = "red") +
  geom_vline(xintercept = cor(y)[1,2], colour = "blue")

s2fit

mean(rho2)

```

### $\eta$ = 2

```{r}

data <- list(N = nrow(y), J = 2, y = y, eta = 2) # uniform on -1 to 1
s2fit <- sampling(ex1, iter = 500, chains = 4, data = data)
s2draws <- extract(s2fit)
Omega <- s2draws$Omega
rho2 <- apply(Omega, 2, function(x) x[,1])[, 2]

qplot(rho2, alpha = I(1/2)) +
  geom_vline(xintercept = mean(rho2), colour = "red") +
  geom_vline(xintercept = cor(y)[1,2], colour = "blue")

s2fit

mean(rho2)
```

# Ref

- [Correlation or no correlation, that is the question](https://www.generable.com/blog/2018/02/correlation-or-no-correlation-that-is-the-question/)
