---
title: loo
author: Masatoshi Katabuchi
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
#rmdformats::material
  html_document:
    fig_caption: yes
    theme: spacelab #readable #sandstone #spacelab #flatly
    highlight: pygments #tango #kate
    toc: TRUE
    toc_depth: 2
    number_sections: TRUE
    toc_float:
      collapsed: TRUE
      smooth_scroll: TRUE
      toc: true
---

```{r, echo = F}
rm(list = ls())
```

```{r, message=FALSE}
library(tidyverse)
```

# loo

Smaller loo (approximate leave-one-out cross-validation) indicates better models in terms of predictive accuracy.

```{r, message=FALSE, eval=TRUE}

d <- read_csv("../loo.csv") %>%
  mutate(loo = round(loo, 2)) 
```

## Table for dry season.

All the models

```{r}
d %>%
  filter(str_detect(file, "dry")) %>%
  DT::datatable(.)
```

Best models

```{r}
tmp <- d %>%
  filter(str_detect(file, "dry")) %>%
  arrange(loo) %>%
  arrange(hab) %>%
  slice(seq(1, 24, by = 6))

tmp %>%
  DT::datatable(.)
```

## Table for wet season.

All the models

```{r}
d %>%
  filter(str_detect(file, "rainy")) %>%
  DT::datatable(.)
```

Best models

```{r}
tmp2 <- d %>%
  filter(str_detect(file, "rainy")) %>%
  arrange(loo) %>%
  arrange(hab) %>%
  slice(seq(1, 24, by = 6)) 

tmp2 %>%
  DT::datatable(.)
```

