---
title: Summary table
author: Masatoshi Katabuchi
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
#rmdformats::material
  html_document:
    fig_caption: yes
    theme: spacelab #readable #sandstone #spacelab #flatly
    highlight: pygments #tango #kate
    toc: TRUE
    toc_depth: 2
    number_sections: TRUE
    toc_float:
      collapsed: TRUE
      smooth_scroll: TRUE
      toc: true
---


```{r global_options, include=FALSE}
library(knitr)
basename <- "seedling-stan"
opts_chunk$set(fig.path = paste0("components/figure/", basename, "-"),
               cache.path = paste0("components/cache/", basename, "/"))
knitr::opts_chunk$set(echo=TRUE,
                      #cache.lazy=FALSE,
                      cache=FALSE,
                      warning=FALSE,
                      message=FALSE)
```


# Deps

```{r}
library(tidyverse)
library(rstan)
#library(coefplot)
library(bayesplot)
library(kableExtra)
options(mc.cores = parallel::detectCores())
```

# Model

```{r,eval = T}
writeLines(readLines("../model/model_inter.stan"))
```

# Dry

```{r}
load("../rda/dry_spab_50_model_inter_full_WD_Full_simple.rda")
```

```{r beta}

tic()
post <- as.data.frame(fit)
toc()


get_beta <- \(fit) {
  post <- as.data.frame(fit)
  tmp <- names(post)
  beta_name <- tmp[str_detect(tmp, "beta")]
  post[, beta_name]
}

post_beta <- get_beta(fit)

```

Posterior means of $\beta$ for each species.

```{r beta-hist}

mean_ <- apply(post_beta, 2, mean)
beta_dat <- tibble(beta = mean_,
  para = rep(colnames(Xd), each = list_dat_d$J))

beta_dat |>
  ggplot(aes(beta )) +
  geom_histogram(bins = 10) +
  geom_vline(xintercept = 0, lty = 2) +
  facet_wrap(~ para, scale = "free") +
  theme_bw()

```

```{r mcmc}

get_gamma <- \(fit) {
  post <- as.data.frame(fit)
  n_para <- fit@par_dims$gamma[1]
  gammas <- str_c("gamma[",rep(1:n_para, each = 11), ",", 1:11,"]")
  post[, gammas]
}

post_gamma <- get_gamma(fit)

#matrix(gammas, ncol = 6, nrow = 11)

```

```{r table}

tb_fun <- \(post_gamma) {
  mean_ <- apply(post_gamma, 2, mean)  |> round(3)
  sd_ <- apply(post_gamma, 2, sd)  |> round(3)
  upper <- apply(post_gamma, 2, function(x)quantile(x, 0.975))
  lower <-  apply(post_gamma, 2, function(x)quantile(x, 0.025))

  m0 <- paste0(mean_, " (", sd_, ")")
  m <- matrix(m0, ncol = 6, nrow = 11)
  colnames(m) <- colnames(Ud)

  sig <- matrix(upper * lower, ncol = 6, nrow = 11)

  for (i in 1:nrow(m)) {
    for (j in 1:ncol(m)) {
      if (sig[i, j] > 0) {
        m[i, j] <- paste0("**", m[i, j], "**")
      }
    }
  }
  tb <- bind_cols(parameters = colnames(Xd), m)
  tb
}

tb_fun(post_gamma) |>
  kable(format = "html") |>
  kable_styling()

```

# Wet

```{r}
load("../rda/rainy_spab_50_model_inter_full_WD_Full_simple.rda")
fit_wet <- fit
```

```{r beta-wet2}
post_beta2 <- get_beta(fit_wet)
```

```{r beta-hist-wet}

mean_ <- apply(post_beta2, 2, mean)
beta_dat <- tibble(beta = mean_,
  para = rep(colnames(Xd), each = list_dat_d$J))

beta_dat |>
  ggplot(aes(beta )) +
  geom_histogram(bins = 10) +
  geom_vline(xintercept = 0, lty = 2) +
  facet_wrap(~ para, scale = "free") +
  theme_bw()

```

```{r mcmc2}
get_gamma2 <- \(fit) {
  post <- as.data.frame(fit)
  gammas <- str_c("gamma[",rep(1:2, each = 11), ",", 1:11,"]")
  post[, gammas]
}

post_gamma2 <- get_gamma2(fit_wet)
```

```{r table2}
tb_fun2 <- \(post_gamma) {
  mean_ <- apply(post_gamma, 2, mean)  |> round(3)
  sd_ <- apply(post_gamma, 2, sd)  |> round(3)
  upper <- apply(post_gamma, 2, function(x)quantile(x, 0.975))
  lower <-  apply(post_gamma, 2, function(x)quantile(x, 0.025))

  m0 <- paste0(mean_, " (", sd_, ")")
  m <- matrix(m0, ncol =2 , nrow = 11)
  colnames(m) <- colnames(Ud)

  sig <- matrix(upper * lower, ncol =2 , nrow = 11)

  for (i in 1:nrow(m)) {
    for (j in 1:ncol(m)) {
      if (sig[i, j] > 0) {
        m[i, j] <- paste0("**", m[i, j], "**")
      }
    }
  }
  tb <- bind_cols(parameters = colnames(Xd), m)
  tb
}

tb_fun2(post_gamma2) |>
  kable(format = "html") |>
  kable_styling()

```

# Computing Environment

```{r}
devtools::session_info()
```

```{r, eval=FALSE}

load("./rda/dry_spab_50_model_inter_full_WD_Full_simple.rda")
fit1 <- fit
#loo1 <- loo(fit1)
load("./rda/dry_spab_50_model_inter_full_WD_Full.rda")
fit2 <- fit
#loo2 <- loo(fit2)
s1 <- data.frame(summary(fit1)$summary)
s2 <- data.frame(summary(fit2)$summary)
```