---
title: "Report"
author: "Masatoshi Katabuchi"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    fig_caption: yes
    theme: spacelab #readable #sandstone #spacelab #flatly
    highlight: pygments #tango #kate
    toc: TRUE
    toc_depth: 2
    number_sections: TRUE
    toc_float:
     collapsed: TRUE
     smooth_scroll: TRUE
     toc: true
---

```{r global_options, include=FALSE}
library(knitr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE,
  cache = FALSE,
  fig.align = "center",
  fig.show = "hold"
)
```

```{r}
targets::tar_load(fit_1_dry_full_int_summary_model_ind)
targets::tar_load(fit_2_wet_full_int_summary_model_ind)
targets::tar_load(fit_3_dry_wd_int_summary_model_ind)
targets::tar_load(fit_4_wet_wd_int_summary_model_ind)
targets::tar_load(fit_5_dry_pca_int_summary_model_ind)
targets::tar_load(fit_6_wet_pca_int_summary_model_ind)
targets::tar_load(fit_7_dry_full_noint_summary_model_ind)
targets::tar_load(fit_8_wet_ful_noint_summary_model_ind)

targets::tar_load(fit_1_dry_full_int_diagnostics_model_ind)
targets::tar_load(fit_2_wet_full_int_diagnostics_model_ind)
targets::tar_load(fit_3_dry_wd_int_diagnostics_model_ind)
targets::tar_load(fit_4_wet_wd_int_diagnostics_model_ind)
targets::tar_load(fit_5_dry_pca_int_diagnostics_model_ind)
targets::tar_load(fit_6_wet_pca_int_diagnostics_model_ind)
targets::tar_load(fit_7_dry_full_noint_diagnostics_model_ind)
targets::tar_load(fit_8_wet_full_noint_diagnostics_model_ind)
```

```{r}
targets::tar_load(test_dry_summary_model_no_like)
targets::tar_load(test_wet_summary_model_no_like)
targets::tar_load(test_dry_diagnostics_model_no_like)
targets::tar_load(test_wet_diagnostics_model_no_like)

library(tidyverse)
test_dry_summary_model_no_like |> filter(rhat > 1.1)
test_wet_summary_model_no_like |> filter(rhat > 1.1)

div_check(test_dry_diagnostics_model_no_like)
div_check(test_wet_diagnostics_model_no_like)

```

```{r}
fit_1_dry_full_int_summary_model_ind
```

```{r}
fit_2_wet_full_int_summary_model_ind
```

```{r}

fit_3_dry_wd_int_summary_model_ind |>
  filter(rhat > 1.1)

fit_4_wet_wd_int_summary_model_ind |>
  filter(rhat > 1.1)

```

```{r}
fit_5_dry_pca_int_summary_model_ind
```

```{r}
fit_6_wet_pca_int_summary_model_ind
```


```{r}
div_check(fit_1_dry_full_int_diagnostics_model_ind)
div_check(fit_2_wet_full_int_diagnostics_model_ind)
div_check(fit_3_dry_wd_int_diagnostics_model_ind)
div_check(fit_4_wet_wd_int_diagnostics_model_ind)
div_check(fit_5_dry_pca_int_diagnostics_model_ind)
div_check(fit_6_wet_pca_int_diagnostics_model_ind)
div_check(fit_7_dry_full_noint_diagnostics_model_ind)
div_check(fit_8_wet_full_noint_diagnostics_model_ind)
```
