---
title: "Diagnostics for MCMC"
author: "Masatoshi Katabuchi"
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontsize: 12pt
format:
  html:
    theme: cosmo #readable #sandstone #spacelab #flatly
    # highlight: pygments #tango #kate
    toc: true
    toc-depth: 2
    number-sections: true
    smooth-scroll: true
    # fontsize: medium
    # toc_float:
    #  collapsed: TRUE
    #  smooth_scroll: TRUE
    #  toc: true
---

```{r global_options, include=FALSE}
library(knitr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE,
  cache = FALSE,
  fig.align = "center",
  fig.show = "hold"
)
```

```{r}
library(tidyverse)
library(targets)
library(kableExtra)
library(here)
library(jsonlite)
source(here("R", "stan.R"))
```

# MCMC diagnostics

```{r}
withr::with_dir(rprojroot::find_root('_targets.R'),
  targets::tar_read(fit_diagnostics_logistic_phy_season_ab)) |>
  div_check()
withr::with_dir(rprojroot::find_root('_targets.R'),
  targets::tar_read(fit_diagnostics_logistic_phy_season_ba)) |>
  div_check()
withr::with_dir(rprojroot::find_root('_targets.R'),
  targets::tar_read(fit_diagnostics_logistic_phy_season_both)) |>
  div_check()
withr::with_dir(rprojroot::find_root('_targets.R'),
  targets::tar_read(fit_diagnostics_logistic_het_season_ab)) |>
  div_check()
withr::with_dir(rprojroot::find_root('_targets.R'),
  targets::tar_read(fit_diagnostics_logistic_het_season_ba)) |>
  div_check()
withr::with_dir(rprojroot::find_root('_targets.R'),
  targets::tar_read(fit_diagnostics_logistic_het_season_both)) |>
  div_check()
```

```{r}
withr::with_dir(rprojroot::find_root('_targets.R'),
  targets::tar_read(fit_diagnostics_logistic_phy_rain_ab)) |>
  div_check()
withr::with_dir(rprojroot::find_root('_targets.R'),
  targets::tar_read(fit_diagnostics_logistic_phy_rain_ba)) |>
  div_check()
withr::with_dir(rprojroot::find_root('_targets.R'),
  targets::tar_read(fit_diagnostics_logistic_phy_rain_both)) |>
  div_check()
withr::with_dir(rprojroot::find_root('_targets.R'),
  targets::tar_read(fit_diagnostics_logistic_het_rain_ab)) |>
  div_check()
withr::with_dir(rprojroot::find_root('_targets.R'),
  targets::tar_read(fit_diagnostics_logistic_het_rain_ba)) |>
  div_check()
withr::with_dir(rprojroot::find_root('_targets.R'),
  targets::tar_read(fit_diagnostics_logistic_het_rain_both)) |>
  div_check()
```


```{r}
mcmc_names <- expand_grid(a1 = c("phy", "het"), a2 = c("season", "rain"), a3 = c("ab", "ba", "both")) |>
  mutate(model = str_c("fit_mcmc_logistic", a1, a2, a3, sep = "_")) |>
  pull(model)

loo_names <- str_c("loo_", mcmc_names)

for (i in 1:12) {
withr::with_dir(rprojroot::find_root('_targets.R'),
  targets::tar_load(loo_names[i]))
}

loo::loo_compare(
   loo_fit_mcmc_logistic_het_rain_ab,
   loo_fit_mcmc_logistic_het_rain_ba,
   loo_fit_mcmc_logistic_het_rain_both,
   loo_fit_mcmc_logistic_phy_rain_ab,
   loo_fit_mcmc_logistic_phy_rain_ba,
   loo_fit_mcmc_logistic_phy_rain_both,
   loo_fit_mcmc_logistic_het_season_ab,
   loo_fit_mcmc_logistic_het_season_ba,
   loo_fit_mcmc_logistic_het_season_both,
   loo_fit_mcmc_logistic_phy_season_ab,
   loo_fit_mcmc_logistic_phy_season_ba,
   loo_fit_mcmc_logistic_phy_season_both) |>
  print()

loo::loo_compare(
   het_ab = loo_fit_mcmc_logistic_het_season_ab,
   het_ba = loo_fit_mcmc_logistic_het_season_ba,
   het_both = loo_fit_mcmc_logistic_het_season_both,
   phy_ab = loo_fit_mcmc_logistic_phy_season_ab,
   phy_ba = loo_fit_mcmc_logistic_phy_season_ba,
   loo_fit_mcmc_logistic_phy_season_both) |>
  print()

```


```{r, eval=FALSE}

d <- read_csv("data/seedling.csv")

d2 <- d |>
  dplyr::select(RF, year, season) |> unique()

model <- lm(RF ~ season, d2)


d2   |>
  group_by(season) |>
  summarise(mean_ = mean(RF))

ggplot(d2 |> filter(season == "rainy"), aes(x = year, y = RF, col = season)) +
  geom_point()

mcmc_names <- expand_grid(a1 = c("phy", "het"), a2 = c("season", "rain", "cont"), a3 = c("ab", "ba", "both")) |>
  mutate(model = str_c("fit_mcmc_logistic", a1, a2, a3, sep = "_")) |>
  pull(model)


draws_df <- tar_read(fit_draws_logistic_het_season_ba)
post <- tar_read(fit_mcmc_logistic_het_season_ba)

d1 <- tar_read(het_season_ba)
s1 <- tar_read(fit_summary_logistic_het_season_ba) |>
  mutate(sig = ifelse(q2.5 * q97.5 > 0, "sig", "ns"))

s1 |>
  filter(str_detect(variable, "gamma")) |>
  filter(sig == "sig") |>
  pull(variable)

d1$x |> colnames()

d1$u |> rownames()

s1 |>
  filter(str_detect(variable, "sig\\["))

dim(draws)
draws <- post$draws()
str(draws2)

color_scheme_set("mix-brightblue-gray")
mcmc_trace(
  draws,
  pars = "gamma[9,2]"
)

mcmc_trace(
  draws,
  regex_pars = "gamma\\[7"
)

mcmc_areas(
  draws,
  regex_pars = "gamma\\[7"
)

d1$x |> colnames()
d1$x |> head()

d1$u[,1]

apply(d1$u, 1, sd)


```
