---
fontsize: 12pt
geometry: margin=1in
link-citations: yes
csl: templates/ecology-letters.csl
bibliography: templates/seedling.bib
crossref:
  fig-title: Fig.
  fig-prefix: Fig.
  eq-prefix: Eq.
format:
  html:
    theme: spacelab #readable #sandstone #spacelab #flatly
    toc: true
    toc-depth: 2
    toc-title: Contents
    self-contained: true
    smooth-scroll: true
    highlight-style: github
  docx:
    toc: false
    number-sections: false
    highlight-style: github
    html-math-method: katex
  pdf:
    toc: false
    keep-tex: true
    pdf-engine: pdflatex
    include-in-header:
      text: |
        \usepackage{xr}
        \usepackage[default]{sourcesanspro}
        \usepackage{sourcecodepro}
        \usepackage{lineno}
        \linenumbers
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

# Model

We modeled the seedling survival for the dry and rainy seasons separately.
Since the effect of tree neighbors on seedling survival is nonlinear on a logistic scale [@Detto2019], we performed a grid-search for the scaling parameter *c* between 0 and 1 in 0.01 increments that maximized the likelihood of the following survival model,

$$
\mathrm{logit}(p_i) = b_0 + b_1 Z_{1i}^c + b_2 Z_{2i}^c,
$$

where $p_i$ is the individual survival probability in the *i*th census interval, and $Z_1$ and $Z_2$ are distance-weighted sums of basal areas of conspecifics and heterospecifics respectively.
We found that $c$ = 0.27 for the dry season and $c$ = 0.24 for the rainy season were the best estimates for our dataset.

We built Bayesian hierarchical models that include variation among species in the effects of conspecific and heterospecific neighbours, and rainfall on survival.
Survival ($s$) of seedling record *i* of individual *m* for species *j* in census *t* in plot *p* was modeled using the Bernoulli distribution ($\mathcal{B}$):

$$
s_{i,j,m,t,p} \sim \mathcal{B}(p_{i, j, t, p}),
$$

$$
\mathrm{logit}(p_{i,j,t,p}) = \boldsymbol{x_{i}} \cdot \boldsymbol{\beta_{j}} + \phi_p + \omega_t,
$$

where $\boldsymbol{\beta_{j}} = \left[\beta_{1,j}, \beta_{2,j}, \ldots, \beta_{K,j} \right]$ is the coefficient row *K*-vector for species *j*,
*K* is the number of predictors for an individual seedling,
$\boldsymbol{x_i} = \left[x_{i,1},x _{i,2}, \ldots,x_{i,K} \right]$ is the vector of predictors of size *K* for an individual seedling,
$\phi_p$ is the random effect for seedling plots, and
$\omega_t$ is the random effect for different census
(note that $\cdot$ denotes dot product).
The set of predictor variables ($\boldsymbol{x_i}$) includes
intercept,
log of seedling heights,
rainfall,
densities of conspecific (*ConS*) and heterospecific (*HetS*) seedlings,
densities of conspecific (*ConA*) and heterospecific (*HetA*) trees that are scaled by 0.27 for the dry season or 0.24 for the rainy season,
and the interactions of rains with *ConS*, with *HetS*, with *ConA* and with *HetA*.
We also considered models with phylogenetic density effects instead of heterospecific density effects.

In the species-level regression, the row vector of coefficients ($\boldsymbol{\beta_{1-K}}$) of each species *j* were assumed to have a multivariate normal distribution through the Cholesky factorization [@StanDevelopmentTeam2021],

$$
\boldsymbol{\beta_j} = \boldsymbol{\gamma_k} \cdot \boldsymbol{u_j} + \mathrm{diag}(\boldsymbol{\sigma})\cdot \boldsymbol{L} \cdot \boldsymbol{z},
$$

where $\boldsymbol{u_{j}} = \left[u_{1,j}, u_{2,j}, \ldots, u_{L,j} \right]$ is the row vector of predictors of size *L* for species *j*,
*L* is the number of predictors for each species (i.e., the number of traits including an intercept),
$\boldsymbol{\gamma_k} = \left[\gamma_{k,1}, \gamma_{k,2}, \ldots, \gamma_{k,L} \right]$ is the coefficient *L*-vector for *k*th predictor in the individual-level regression,
$\mathrm{diag}(\boldsymbol{\sigma})$ is the diagonal matrix with the diagonal vector of coefficient scales,
$\boldsymbol{L}$ is the Cholesky factor of the original correlation matrix which can be derived using a Cholesky decomposition for the covariance matrix of the original multivariate normal distribution,
$\boldsymbol{z}$ is a *K* $\times$ *J* matrix of latent Gaussian variables, and
*J* is the number of species.
The set of species-level predictor variables ($\boldsymbol{u_j}$) includes
1)
LDMC,
SDMC,
LA,
SLA,
Chl,
LT,
$\delta$C~13~,
C,
N, and
$\pi$~tlp~,
2) abundance,
3) basal area,
4) abundance and basal area, and
5) abundance, basal area and their interactions.
The row vector $\gamma_{k,1}$ represents average effects of the each individual-level predictor (e.g., *ConS*) across species,
whereas $\gamma_{k, l}$ ($l \ne 1$), represents the effects of the *l*-th individual-level predictor (e.g., SLA) on the variation in the strength of the each individual-level predictor (e.g., variation in the strength of *ConS* among species).
To allow comparisons among parameter estimates, the individual-level predictors ($\boldsymbol{x_i}$) and the species-level predictors ($\boldsymbol{u_j}$) were scaled to a mean of 0 and standard deviation of 1 within each season and across species, respectively.

Posterior distributions of all parameters were estimated using the Hamiltonian Monte Carlo algorithm (HMC) implemented in Stan [@Carpenter2017] using the weakly-informative priors [@Gelman2008].
Convergence of the posterior distribution was assessed with the Gelman-Rubin statistic with a convergence threshold of 1.1 [@Gelman2013] and effective sample sizes > 400 [@Vehtari2021] for all parameters.
All statistical analyses were conducted in R version 4.2.1 [@RCoreTeam2022] using the R package *targets* version 0.13.5 for workflow management [@Landau2021].
Codes and datasets are available at
https://github.com/mattocci27/trait-ndd
and
XXXX,
respectively.
