---
geometry: margin=1in
link-citations: yes
csl: templates/american-journal-of-botany.csl
bibliography: Seedling.bib
fontsize: 12pt
#font-famliy: "ebgaramond"
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{xcolor}
  - \usepackage{lineno}
  - \linenumbers
output:
  html_document:
    toc: FALSE
  pdf_document:
    keep_md: false
    fig_caption: yes
    keep_tex: yes
    toc: no
    number_sections: no
    template: templates/eisvogel2.tex
    #template: null
    pandoc_args:
      - "--filter"
      - "pandoc-crossref"
  bookdown::word_document2:
    fig_width: 6
    fig_caption: yes
    toc: FALSE
    reference_docx: templates/rmd_style.docx
    pandoc_args:
    - "--filter"
    - "pandoc-crossref"
    - "--mathml"
---

```{r caching, include=FALSE}
library(knitr)
library(tidyverse)
library(methods)
#source("../scripts/rmd_func.R")
#basename <- "LMA_method"
opts_chunk$set(fig.path = paste("figs/", sep=""))
opts_chunk$set(tidy=FALSE, warning=FALSE, message=FALSE,
               comment = NA, verbose = TRUE, echo=FALSE)
# PDF-based figures
opts_chunk$set(dev='pdf')

# https://github.com/haozhu233/kableExtra/issues/477
options(kableExtra.auto_format = FALSE)
library(kableExtra)

#val <- yaml::yaml.load_file("../values.yml")
```

# Model

We modeled the seedling survival for the dry and rainy seasons separately, in order to better understanding the seasonal dynamics of seedling community.

## Neighbor densities

Since the effect of adult neighbors on seedling survival is nonlinear in the logistic scale [@Detto2019], we performed a grid-search for the scaling parameter $c$ between 0 and 1 in 0.01 increments that maximized the likelihood of the following survival model,

$$
\mathrm{logit}(p_i) = b_0 + b_1 Z_{1i}^c + b_2 Z_{2i}^c
$$

where $p_i$ is the individual survival probability in the *i*th census interval, and $Z_1$ and $Z_2$ are distance-weighted sums of basal areas of conspecifics and heterospecifics respectively.
We found that $c$ = 0.24 for the dry season and $c$ = 0.27 for the rainy season were the best estimates for our dataset.

## Survival model

We then build Bayesian hierarchical models that include variation among species in the effects of conspecific and heterospecific neighbours, and rainfall on survival.
Survival ($s$) of seedling *i* of individual *m* for species *j* in census *t* in plot *p*  was modeled using the Bernoulli distribution ($\mathcal{B}$) :

$$
s_{i,j,m,t,p} \sim \mathcal{B}(p_{i, j, m, t, p})
$$

$$
\mathrm{logit}(p_{i,j,m,t,p}) = \boldsymbol{\beta_{j}} \cdot \boldsymbol{z_{i}} + \phi_p + \omega_t + \psi_m
$$

where $\boldsymbol{\beta_{j}} = \left[\beta_{j,1}, \beta_{j,2}, \ldots, \beta_{j,k} \right]$ is the coefficient *k*-vector for species *j*,
*k* is the number of predictors for an individual seedling,
$\boldsymbol{z_i} = \left[z_{1,i}, z_{2,i}, \ldots, z_{k,i} \right]$ is the row vector of predictors of size *k* for an individual seedling,
$\phi_p$ is the random effect for seedling plots,
$\omega_t$ is the random effect for different census, and
$\psi_m$ is the random effect for the repeated observations of the same individuals
(note that $\cdot$ denotes dot product).
The set of predictor variables ($z_{k,i}$) includes
intercept,
log of seedling heights,
rainfall,
densities of conspecific (CONS) and heterospecific (HETS) seedlings,
densities of conspecific (CONA) and heterospecific (HETA) adult trees that are scaled by 0.24 for the dry season or 0.27 for the rainy season,
and the interactions of rains with CONS, with HETS, with CONA and with HETA.

In the species-level regression, the vector of coefficients ($\beta_{0-k}$) of each species *j* were assumed to have a multivariate normal distribution ($\mathcal{MVN}$);

$$
\boldsymbol{\beta_j} \sim  \mathcal{MVN}(\boldsymbol{x_j} \cdot \boldsymbol{\gamma_k}, {\boldsymbol \Sigma_{\beta}})
$$

where $\boldsymbol{x_{j}} = \left[x_{j,1}, x_{j,2}, \ldots, x_{j,l} \right]$ is the vector of predictors of size *l* for each species,
*l* is the number of predictors for each species,
$\boldsymbol{\gamma_i} = \left[\gamma_{1,k}, \gamma_{2,k}, \ldots, \gamma_{l,k} \right]$ is the the coefficient *l*-vector for species *j* and
$\boldsymbol{\Sigma_{\beta}}$ is the covariance matrix.

In the species-level regression, the vector of coefficients ($\beta_{0-k}$) of each species *j* were assumed to have a multivariate normal distribution through the Cholesky factorization,

$$
\boldsymbol{\beta_j} = \boldsymbol{x_j} \cdot \boldsymbol{\gamma_k} + (\mathrm{diag}(\boldsymbol{\sigma})\cdot \boldsymbol{L} \cdot \boldsymbol{u})^\top
$$

where $\boldsymbol{x_{j}} = \left[x_{j,1}, x_{j,2}, \ldots, x_{j,l} \right]$ is the vector of predictors of size *l* for each species,
*l* is the number of predictors for each species,
$\boldsymbol{\gamma_i} = \left[\gamma_{1,k}, \gamma_{2,k}, \ldots, \gamma_{l,k} \right]$ is the the coefficient *l*-vector for species *j* ,
$\mathrm{diag}(\boldsymbol{\sigma})$ is the diagonal matrix with the diagonal vector of coefficient scales,
$\boldsymbol{L}$ is the Cholesky factor of the original correlation matrix which can be derived using a Cholesky decomposition for the covariance matrix of the original multivariate normal distribution,
$\boldsymbol{u}$ is a $k \times j$ matrix of latent Gaussian variables, and
$\top$ denotes the conjugate transpose.
The set of predictor variables ($x_{j,l}$) includes
LDMC,
SDMC,
LA,
SLA,
Chl,
LT,
C13,
C,
N,
CN, and
tlp (**need to edit here according to a trait description section**).

Posterior distributions of all parameters were estimated using the Hamiltonian Monte Carlo algorithm (HMC) implemented in Stan [@Carpenter2017] using the weakly-informative priors [@Gelman2008].
See supplement X for more detail.
The Stan code use to fit models is available from Github at: XXXX.
Convergence of the posterior distribution was assessed with the Gelman-Rubin statistic with a convergence threshold of 1.1 for all parameters [@Gelman2013].

# SI text

## Model estimation

We fitted the parameters using laten Gaussian variables for the species-level coeffcient

\begin{align}
s_{i,j,m,t,p} &\sim \mathcal{B}(p_{i, j, m, t, p}) \\
\boldsymbol{\beta_j} &\sim \mathcal{MVN}(\boldsymbol{x_j} \cdot \boldsymbol{\gamma_k}, {\boldsymbol \Sigma_{\beta}})  \\
\gamma &\sim \mathcal{N}(0, 5) \\
L &\sim \mathrm{LkjCholesky}(2) \\
\tilde{\phi_p}, \tilde{\omega_t}, \tilde{\psi_m}, u &\sim \mathcal{N}(0, 1) \\
\tilde{\tau_{1-3}}, \tilde{\sigma_{1-3}} &\sim \mathcal{U}(0, \pi/2) \\
\beta &= x \cdot \gamma + (\mathrm{diag}(\sigma)\cdot L \cdot u)^\top \\
\tau_{1-3} &= 2.5 \times tan(\tilde{\tau_{1-3}}) \\
\sigma_{1-3} &= 2.5 \times tan(\tilde{\sigma_{1-3}}) \\
\phi_p &= \tau_1 \tilde{\phi_p} \\
\omega_t &= \tau_2 \tilde{\omega_t} \\
\psi_m &= \tau_3 \tilde{\psi_m} \\
\end{align}

parameter

\begin{align}
\mathrm{logit}(p_{i,j,m,t,p}) &= \boldsymbol{\beta_{j}} \cdot \boldsymbol{z_{i}} + \phi_p + \omega_t + \psi_m , \nonumber \\
\tau_{1-3} &= 2.5 \times tan(\tilde{\tau_{1-3}}), \nonumber \\
\sigma_{1-3} &= 2.5 \times tan(\tilde{\sigma_{1-3}}), \nonumber \\
\beta &= x \cdot \gamma + (\mathrm{diag}(\sigma)\cdot L \cdot u)^\top, \nonumber \\
\phi_p &= \tau_1 \tilde{\phi_p}, \nonumber \\
\omega_t &= \tau_2 \tilde{\omega_t}, \nonumber \\
\psi_m &= \tau_3 \tilde{\psi_m}
\end{align}


likelihood

\begin{align}
s_{i,j,m,t,p} &\sim \mathcal{B}(p_{i, j, m, t, p}) , \nonumber \\
\boldsymbol{\beta_j} &\sim \mathcal{MVN}(\boldsymbol{x_j} \cdot \boldsymbol{\gamma_k}, {\boldsymbol \Sigma_{\beta}}) , \nonumber \\
\tilde{\phi_p}, \tilde{\omega_t}, \tilde{\psi_m}, u &\sim \mathcal{N}(0, 1), \nonumber \\
\tilde{\tau_{1-3}}, \tilde{\sigma_{1-3}} &\sim \mathcal{U}(0, \pi/2), \nonumber \\
\gamma &\sim \mathcal{N}(0, 5), \nonumber \\
L &\sim \mathrm{LkjCholesky}(2)
\end{align}



The covariance matrix $\boldsymbol \Sigma_{\beta}$ can be decomposed as ${\boldsymbol \Sigma} = \mathrm {diag}({\boldsymbol \sigma}){\boldsymbol \Omega}\mathrm {diag}({\boldsymbol \sigma}) = \mathrm {diag}({\boldsymbol \sigma})\boldsymbol{LL}^\top \mathrm {diag}({\boldsymbol \sigma})$ using a Cholesky decomposition [@Alvarez2014],
where
$\boldsymbol{L}$ is a Cholesky factor of a correlation matrix ($\boldsymbol \Omega$),
$\boldsymbol{L}^\top$ is the conjugate transpose of $\boldsymbol{L}$, and
$\boldsymbol \sigma$ is the vector of coefficient scales.






## References